In [13]:
board = [[5, 3, 0, 0, 7, 0, 0, 0, 0],
         [6, 0, 0, 1, 9, 5, 0, 0, 0],
         [0, 9, 8, 0, 0, 0, 0, 6, 0],
         [8, 0, 0, 0, 6, 0, 0, 0, 3],
         [4, 0, 0, 8, 0, 3, 0, 0, 1],
         [7, 0, 0, 0, 2, 0, 0, 0, 6],
         [0, 6, 0, 0, 0, 0, 2, 8, 0],
         [0, 0, 0, 4, 1, 9, 0, 0, 5],
         [0, 0, 0, 0, 8, 0, 0, 7, 9]]

In [14]:
print(board)

[[5, 3, 0, 0, 7, 0, 0, 0, 0], [6, 0, 0, 1, 9, 5, 0, 0, 0], [0, 9, 8, 0, 0, 0, 0, 6, 0], [8, 0, 0, 0, 6, 0, 0, 0, 3], [4, 0, 0, 8, 0, 3, 0, 0, 1], [7, 0, 0, 0, 2, 0, 0, 0, 6], [0, 6, 0, 0, 0, 0, 2, 8, 0], [0, 0, 0, 4, 1, 9, 0, 0, 5], [0, 0, 0, 0, 8, 0, 0, 7, 9]]


In [15]:
import numpy as np
print(np.matrix(board))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [16]:
"""
Y will represent the row number of the selected cell
X will represent the column position in that row(Y) 
N will be the possible number(1-9) which can be placed in that cell

"""

'\nY will represent the row number of the selected cell\nX will represent the column position in that row(Y) \nN will be the possible number(1-9) which can be placed in that cell\n\n'

In [17]:
# always the y first then x because this is how the indices appear(in order) in a sysytem
def possible(y, x, n):
    global board # declared globally so that we can modify it 
    for i in range(0, 9):
        if board[y][i] == n: #check if n is already present in whole column 
            return False 
    for i in range(0, 9):
        if board[i][x] == n: #check if n is already present in whole row 
            return False
    
    # now check in the 3*3 matrix 
    
    x0 = (x//3) * 3 #check the output to understand what this does 
    y0 = (y//3) * 3
    
    for i in range(0, 3):
        for j in range(0, 3):
            if board[y0 + i][x0 + j] == n:
                return False
        # If these condition are false implies that n can be a possible solution
        # for that cell, hence return true 
    return True
    

In [18]:
possible(4, 6, 3)

False

In [19]:
def solve():
    global board
    for y in range(0, 9):
        for x in range(0, 9):
            if board[y][x] == 0:
                for n in range(1, 10):
                    if possible(y, x, n):
                        board[y][x] = n
                        solve()
                        board[y][x] = 0 #backtrack 
                return 
    print(np.matrix(board)) 
    input("Other Solution?")

In [20]:
solve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
Other Solution?
